INSERT INTO "Sector"("name") VALUES
 ('9 de Octubre Este')
,('9 de Octubre Oeste')
,('Abel Gilbert')
,('Acuarela')
,('Los Álamos')
,('Alborada Este')
,('Alborada Oeste')
,('Los Almendros')
,('Las Américas')
,('La Atarazana')
,('Ayacucho')
,('Bastión Popular')
,('Batallón del Suburbio')
,('Bellavista')
,('Bolívar')
,('Los Ceibos')
,('Centenario')
,('Cerro del Carmen')
,('El Cóndor')
,('Cuba')
,('Del Astillero')
,('Estero Salado')
,('Los Esteros')
,('La FAE')
,('Febres Cordero')
,('Floresta')
,('La Florida')
,('García Moreno')
,('Garzota')
,('Guangala')
,('Guasmo Este')
,('Guasmo Oeste')
,('Guayacanes')
,('Huancavilca')
,('Isla Trinitaria')
,('Juan Montalvo')
,('Kennedy')
,('Letamendi')
,('Lomas de Prosperina')
,('Luz del Guayas')
,('Mapasingue')
,('Miraflores')
,('Monte Bello')
,('Olmedo')
,('Las Orquídeas Este')
,('Las Orquídeas Oeste')
,('Paraíso')
,('Pascuales')
,('Pedro Carbo')
,('Urbanización Alcance')
,('La Pradera')
,('Prosperina')
,('Puerto Azul Norte')
,('Puerto Azul Sur')
,('Puerto Lisa')
,('Quinto Guayas Este')
,('Quinto Guayas Oeste')
,('Río Guayas')
,('Roca')
,('Rocafuerte')
,('La Saiba')
,('Samanes')
,('San Eduardo')
,('Los Sauces')
,('Simón Bolívar')
,('Sopeña')
,('Sucre')
,('Tarqui')
,('Unión')
,('Urdaneta')
,('Urdenor')
,('Urdesa')
,('Los Vergeles')
,('Ximena')
,('Las Peñas');



INSERT INTO "TypeProperty"("name", "additionalFeatures") VALUES
	 ('Casa', '["bedRooms", "bathRooms", "floors"]'),
	 ('Departamento', '["bedRooms", "bathRooms"]'),
	 ('Local comercial', '["bathRooms"]'),
	 ('Edificio', '["floors"]'),
	 ('Terreno', '[]');
