CREATE TABLE "Role" (
	"id" SERIAL NOT NULL,
	"name" VARCHAR(75) UNIQUE NOT NULL,
	CONSTRAINT "Role_pkey" PRIMARY KEY ("id")
);

create table "User"(
	"id" BIGSERIAL NOT NULL,
	"email" VARCHAR(75) UNIQUE,
	"password" VARCHAR(50) NOT NULL,
	"idCard" VARCHAR(25) UNIQUE NULL,
	"firstName" VARCHAR(100) NOT NULL,
	"lastName" VARCHAR(100) NOT NULL,
	"phone" VARCHAR(25) NULL,
	"createdAt" TIMESTAMPTZ NULL,
	"updatedAt" TIMESTAMPTZ NULL,
	"idRole" INTEGER NOT NULL,
	CONSTRAINT "User_pkey" PRIMARY KEY ("id"),
	CONSTRAINT "User_idRole_fkey" FOREIGN KEY ("idRole") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE
)
