version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PROD_DB_USERNAME}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
